version: '3'

services:
  bind:
    container_name: bind
    hostname: bind
    restart: always
    image: kagurazakanyaa/bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data
